CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    eta INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
